[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
backend = { path = "../backend" }
bincode = "1.3.3"
clap = { version = "4.5.20", features = ["derive"] }
fs-err = "3.1.1"
log = "0.4.27"
simple_logger = "5.0.0"
